$(document).ready(function() {
	$('.nav-toggle-block').click(function() {
		$(this).toggleClass('open');
		$('.nav-toggle-line').toggleClass('active-line');
		$('.nav-list>li').toggleClass('active-list');
		$('.menu-list').slideToggle();
	});

	$('.sections-produse').owlCarousel({
	    lazyLoad:true,
	    loop:true,
	    nav:false,
	    margin:10,
	    responsive:{
			0:{
				items:2
			},
			640:{
				items:4
			},
			960:{
				items:5
			}
		}
	});
	$('.sections-produse-item-page').owlCarousel({
	    lazyLoad:true,
	    loop:true,
	    nav:false,
	    margin:10,
	    responsive:{
			0:{
				items:2
			},
			640:{
				items:4
			},
			960:{
				items:5
			}
		}
	});
});